### ISSUE TITLE
Warning: Couldn't open (repo file)

### ISSUE THREAD

**Issue by ivilata** [equalitie/ipfs-cache#5]
When running the example injector and client built from commit 95aa3380, each with its own repo directory, like this:

```
shell1$ ./cache_injector --repo repo-injector
shell2$ curl -d key=my_key2 -d value=my_value2 localhost:35583
shell3$ ./cache_client --repo repo-client --ipns QmdrWahSdaiDFx7UUbxrn81Fx58kthvqJe6JzaWN4Eqx8L --key my_key2
```

I check that the new value is correctly inserted in IPFS. The client however complains that:

```
Warning: Couldn't open repo-client/ipfs_cache_db.QmdrWahSdaiDFx7UUbxrn81Fx58kthvqJe6JzaWN4Eqx8L.json
Fetching...
Exception
```

But it still exits with code 0.

BTW, copying the contents of the database to that file and running the command again avoids the warning and the exception message, the client still exits with 0 but it shows nothing after ``Fetching...``, while tracing ``db/query_()`` shows that it did retrieve the content hash from the cache, and the content behind that hash is available in IPFS.

**Comment by inetic** [comment]
@ivilata, I made a _partial_ fix in [issue-5](https://github.com/equalitie/ipfs-cache/commit/fb7ed6196a6f59658cf786f514a76293ec63183e) branch. It'll make it not crash, but the client will always print out "key not found" error. Check the commit message for more info.

**Comment by inetic** [comment]
This issue should be resolved by [this commit](https://github.com/equalitie/ipfs-cache/commit/e9cd036654e0135e898fa0458f0ee9c217e666ee).

Note that the `Warning: Couldn't open repo-client/ipfs_cache_db.QmXYZ.json` is harmless. The way ipfs-cache is currently implemented is such that each time the client fetches a database, it also stores the json file on the disk and then tries to load it back when restarted. This is an optimization because, in normal situations it would be good to have the database from the previous run due to IPNS resolving being slow.

It may interfere with debugging however, if so, either do

```
$ rm <repo>/ipfs_cache_db.*.json || true
```

before each test, or we could add an explicit calls to `Client` to load the database from disk (but if the later, we also need to modify ouinet to use it).

**Comment by ivilata** [comment]
It seems to work, the client takes a while while waiting for the next publication of the db, but it fetches the key in the end. Thanks!
